/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screen;
import dao.SolicitudCambioDAO;
import model.SolicitudCambio;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jorgmms
 */
public class AdminSolicitudesForm extends javax.swing.JFrame {

   private void cargarSolicitudesPendientes() {
    // Obtiene el modelo de la tabla (asumiendo que se llama jTable1)
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // Limpia la tabla por si tenía datos viejos
    model.setRowCount(0);

    // Llama al DAO
    SolicitudCambioDAO dao = new SolicitudCambioDAO();
    List<SolicitudCambio> solicitudes = dao.listarTodas();
    
    // Llena la tabla solo con las solicitudes PENDIENTES
    for (SolicitudCambio s : solicitudes) {
        if ("Pendiente".equalsIgnoreCase(s.getEstado())) {
            model.addRow(new Object[]{
                s.getUsuarioEmpleado(),
                s.getFechaInicial(),
                s.getFechaNueva(),
                s.getJustificacion()
                // No mostramos el estado porque ya sabemos que es "Pendiente"
            });
        }
    }
}
    public AdminSolicitudesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnAprobar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Fecha Inicio", "Fecha Fin", "Justificación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 870, 250));

        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 120, 60));

        btnAprobar.setText("Aprobar");
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 210, 40));

        btnRechazar.setText("Rechazar");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 210, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Solicitudes Cambio de Turno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Fondo_principal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarSolicitudesPendientes();
    }//GEN-LAST:event_formWindowOpened

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        // 1. Obtener la fila seleccionada
    int filaSeleccionada = jTable1.getSelectedRow();
    
    // 2. Verificar si se seleccionó algo
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una solicitud de la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 3. Obtener los datos clave de la fila (Usuario y Fecha Inicial)
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String usuario = model.getValueAt(filaSeleccionada, 0).toString();
    String fechaInicial = model.getValueAt(filaSeleccionada, 1).toString();
    
    // 4. Llamar al DAO para actualizar
    SolicitudCambioDAO dao = new SolicitudCambioDAO();
    dao.actualizarEstado(usuario, fechaInicial, "Aprobado");
    
    // 5. Informar al admin y refrescar la tabla
    JOptionPane.showMessageDialog(this, "Solicitud APROBADA.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    cargarSolicitudesPendientes(); // Refresca para que la solicitud desaparezca
    }//GEN-LAST:event_btnAprobarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        // 1. Obtener la fila seleccionada
    int filaSeleccionada = jTable1.getSelectedRow();
    
    // 2. Verificar si se seleccionó algo
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una solicitud de la tabla.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 3. Obtener los datos clave de la fila
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String usuario = model.getValueAt(filaSeleccionada, 0).toString();
    String fechaInicial = model.getValueAt(filaSeleccionada, 1).toString();
    
    // 4. Llamar al DAO para actualizar
    SolicitudCambioDAO dao = new SolicitudCambioDAO();
    dao.actualizarEstado(usuario, fechaInicial, "Rechazado");
    
    // 5. Informar al admin y refrescar la tabla
    JOptionPane.showMessageDialog(this, "Solicitud RECHAZADA.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    cargarSolicitudesPendientes(); // Refresca para que la solicitud desaparezca
    }//GEN-LAST:event_btnRechazarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSolicitudesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSolicitudesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSolicitudesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSolicitudesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSolicitudesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
