
package screen;
import dao.EmpleadoDAO;
import dao.TurnoDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Empleado;
import java.util.List;
import javax.swing.JOptionPane;
import model.Turno;

/**
 *
 * @author erickpedroza
 */
public class GestionTurnosForm extends javax.swing.JFrame {
    

    /**
     * Creates new form GestionTurnosForm
     */
    public GestionTurnosForm() {
        initComponents();
    }
    
    private void cargarEmpleados() {
        EmpleadoDAO dao = new EmpleadoDAO();
        List<Empleado> listaDeEmpleados = dao.obtenerTodos();
        
        // Limpiamos el ComboBox para evitar que se dupliquen datos
        cbxEmpleados.removeAllItems();
        
        // Recorremos la lista y añadimos cada empleado al ComboBox
        for (Empleado emp : listaDeEmpleados) {
            // Filtra para mostrar solo empleados "Activos"
            if ("Activo".equalsIgnoreCase(emp.getEstado()) && !"Administrador".equalsIgnoreCase(emp.getRol()) ) {
                cbxEmpleados.addItem(emp);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbxEmpleados = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 188, 46));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 188, 46));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Inicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 294, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Fin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 85, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 294, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Empleados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turno Matutino\t", "Turno Vespertino", "Turno Nocturno" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 294, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Turnos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 85, 30));

        getContentPane().add(cbxEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 294, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Intro.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MantenimientoForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Empleado empleadoSeleccionado = (Empleado) cbxEmpleados.getSelectedItem();
    Date fechaInicio = jDateChooser1.getDate(); // Suponiendo que jDateChooser1 es para la fecha de inicio
    Date fechaFin = jDateChooser2.getDate();    // Suponiendo que jDateChooser2 es para la fecha de fin
    String turnoSeleccionado = (String) jComboBox1.getSelectedItem(); // Suponiendo que jComboBox1 es para los turnos

    // Validaciones
    if (empleadoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado.");
        return;
    }
    if (fechaInicio == null || fechaFin == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar ambas fechas.");
        return;
    }

    // Formatear las fechas a un texto estándar (YYYY-MM-DD)
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fechaInicioStr = sdf.format(fechaInicio);
    String fechaFinStr = sdf.format(fechaFin);

    // Crear el objeto Turno con los datos del formulario
    Turno nuevoTurno = new Turno();
    nuevoTurno.setUsuarioEmpleado(empleadoSeleccionado.getUsuario());
    nuevoTurno.setFechaInicio(fechaInicioStr);
    nuevoTurno.setFechaFin(fechaFinStr);
    nuevoTurno.setTurno(turnoSeleccionado);
    
    // Guardar el turno usando el DAO
    TurnoDAO turnoDAO = new TurnoDAO();
    turnoDAO.guardarTurno(nuevoTurno);
    
    JOptionPane.showMessageDialog(this, "Asignación Creada con Éxito para " + empleadoSeleccionado.getNombre());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.cargarEmpleados();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTurnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTurnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTurnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTurnosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTurnosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Empleado> cbxEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
