/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;
import dao.MarcajeDAO;
import model.Marcaje;
import java.awt.event.ActionEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Empleado;
/**
 *
 * @author jorgmms
 */
public class MarcajeForm extends javax.swing.JFrame {
    
    private Marcaje marcajeActual;
    private final MarcajeDAO marcajeDAO;
    private final Empleado empleadoLogueado;
    private Timer timer;
    
    
    /**
     *
     * @param usuario
     */
    public MarcajeForm(Empleado empleado) {
        initComponents();
        this.empleadoLogueado = empleado; // Guardamos el objeto Empleado
        this.marcajeDAO = new MarcajeDAO();
        this.setLocationRelativeTo(null);
        iniciarReloj();
        actualizarEstadoBotones();
    }

    

    private void iniciarReloj() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm:ss a");
        timer = new Timer(1000, e -> {
            lblTimer.setText(LocalTime.now().format(formatter));
            
        });
        timer.start();
    }
    
    // CENTRALIZA LA LOGICA HABILITANDO Y DESHABILITANDO LOS BOTONES
    // BASANDOSE EN EL ESTADO DEL OBJETO marcajeActual.
    
    private void actualizarEstadoBotones() {
        
        boolean sinMarcaje = (marcajeActual == null);
        
        btnEntrada.setEnabled(sinMarcaje);
        
        btnDescansoUno.setEnabled(!sinMarcaje && marcajeActual.getHoraDescanso1() ==  null);
        
        btnDescansoDos.setEnabled(!sinMarcaje && marcajeActual.getHoraDescanso1() != null && marcajeActual.getHoraDescanso2() == null);
        
        btnSalida.setEnabled(!sinMarcaje && marcajeActual.getHoraDescanso2() != null && marcajeActual.getHoraSalida() == null);
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        btnDescansoUno = new javax.swing.JButton();
        btnDescansoDos = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnInfoMarcaje = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTimer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrada.setText("ENTRADA");
        btnEntrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 220, 40));

        btnDescansoUno.setText("DESCANSO 1");
        btnDescansoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescansoUnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescansoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 220, 40));

        btnDescansoDos.setText("DESCANSO 2");
        btnDescansoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescansoDosActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescansoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 220, 40));

        btnSalida.setText("SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 220, 40));

        btnInfoMarcaje.setText("INFO DE MARCAJE");
        btnInfoMarcaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoMarcajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnInfoMarcaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 220, 40));

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 140, 40));

        lblTimer.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jPanel1.add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Couverture (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoMarcajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoMarcajeActionPerformed
        InfoMarcajeForm infoForm = new InfoMarcajeForm(this.empleadoLogueado.getUsuario());
        infoForm.setVisible(true);
    }//GEN-LAST:event_btnInfoMarcajeActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        this.marcajeActual = new Marcaje(this.empleadoLogueado.getUsuario());
        this.marcajeActual.setHoraEntrada(LocalTime.now());
       
        if (marcajeActual.getHoraEntrada().isAfter(LocalTime.of(8, 0))) {
            JOptionPane.showMessageDialog(this, "Entrada tarde registrada", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Entrada registrada: " + marcajeActual.getHoraEntrada());
        }
        
        actualizarEstadoBotones(); // Actualizamos la UI
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnDescansoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescansoUnoActionPerformed
        if (marcajeActual == null) {
            JOptionPane.showMessageDialog(this, "Debe marcar la entrada primero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        marcajeActual.setHoraDescanso1(LocalTime.now()); // <-- CORRECCIÓN CRÍTICA: Guardar la hora
        JOptionPane.showMessageDialog(this, "Descanso 1 registrado: " + marcajeActual.getHoraDescanso1(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        actualizarEstadoBotones(); // Actualizamos la UI
    }//GEN-LAST:event_btnDescansoUnoActionPerformed

    private void btnDescansoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescansoDosActionPerformed
            if (marcajeActual == null || marcajeActual.getHoraDescanso1() == null) {
            JOptionPane.showMessageDialog(this, "Debe marcar el primer descanso primero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        marcajeActual.setHoraDescanso2(LocalTime.now()); // <-- CORRECCIÓN CRÍTICA: Guardar la hora
        JOptionPane.showMessageDialog(this, "Descanso 2 registrado: " + marcajeActual.getHoraDescanso2(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        actualizarEstadoBotones(); // Actualizamos la UI
    }//GEN-LAST:event_btnDescansoDosActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        if (marcajeActual == null || marcajeActual.getHoraDescanso2() == null) {
            JOptionPane.showMessageDialog(this, "Debe marcar ambos descansos primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        marcajeActual.setHoraSalida(LocalTime.now());

        try {
            marcajeDAO.guardar(marcajeActual);
            JOptionPane.showMessageDialog(this, "Salida registrada: " + marcajeActual.getHoraSalida() + "\nEl marcaje completo ha sido guardado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Reinicia todo para el siguiente marcaje
            marcajeActual = null;
            actualizarEstadoBotones(); // Actualizamos la UI al estado inicial

        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Error crítico al guardar el archivo: " + e.getMessage(), "Error de Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if (timer != null) {
        timer.stop();
    }
        this.dispose();
    // Le pasamos el objeto Empleado completo de vuelta al panel
        PanelDeEmpleado panel = new PanelDeEmpleado(this.empleadoLogueado);
        panel.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void  initComponets() {
        lblTimer = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        btnDescansoUno = new javax.swing.JButton();
        btnDescansoDos = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnInfoMarcaje = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Marcaje"); 
        
        lblTimer.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("00:00:00");
        
        btnEntrada.setText("Marcar Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        
        btnDescansoUno.setText("Marcar Descanso 1");
        btnDescansoUno.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                 btnDescansoUnoActionPerformed(evt);
            }
        });
        
        btnDescansoDos.setText("Marcar Descanso 2");
        btnDescansoDos.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescansoDosActionPerformed(evt);
            }
        });
        
        btnSalida.setText("Marcar Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            @Override    
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        
        btnInfoMarcaje.setText("Información del Marcaje");
        btnInfoMarcaje.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoMarcajeActionPerformed(evt);
            }
        });
        
         btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnDescansoUno, javax.swing.GroupLayout.DEFAULT_SIZE, 
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnDescansoDos, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnSalida, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnInfoMarcaje, javax.swing.GroupLayout.DEFAULT_SIZE, 
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addContainerGap() 
        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnEntrada)
        .addGap(18, 18, 18)
        .addComponent(btnDescansoUno)
        .addGap(18, 18, 18)
        .addComponent(btnDescansoDos)
        .addGap(18, 18, 18)
        .addComponent(btnSalida)
        .addGap(18, 18, 18)
        .addComponent(btnInfoMarcaje)
        .addGap(18, 18, 18)
        .addComponent(btnRegresar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    pack();
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescansoDos;
    private javax.swing.JButton btnDescansoUno;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnInfoMarcaje;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables
}
