/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;
import javax.swing.JOptionPane;
import screen.MarcajeForm;
import model.Empleado;
import screen.AsignacionTurnosEmpleado;
/**
 *
 * @author jorgmms
 */
public class PanelDeEmpleado extends javax.swing.JFrame {

    // Variable para guardar al empleado (ya deberías tenerla)
    private Empleado empleadoLogueado;

    /**
     * Constructor que recibe al empleado que inició sesión.
     */
    public PanelDeEmpleado(Empleado empleado) {
        // 1. Inicializa los componentes visuales del formulario. ¡Esta línea es vital!
        initComponents();
        
        // 2. Guarda el objeto del empleado que recibiste para usarlo más tarde.
        this.empleadoLogueado = empleado;
        
        // 3. (Opcional) Usa los datos del empleado para personalizar la ventana.
        this.setTitle("Panel de - " + this.empleadoLogueado.getNombre());
        this.setLocationRelativeTo(null);   
    }
    
    public PanelDeEmpleado(String nombreUsuario) {
    initComponents();
    this.setLocationRelativeTo(null);
    
    this.empleadoLogueado = new Empleado();
    this.empleadoLogueado.setUsuario(nombreUsuario);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtMarcaje = new javax.swing.JButton();
        ButtSoliAusencia = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnVerTurnos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtMarcaje.setText("Marcaje");
        ButtMarcaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtMarcajeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtMarcaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 250, 60));

        ButtSoliAusencia.setText("Solicitud De Ausencia");
        ButtSoliAusencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtSoliAusenciaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtSoliAusencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 250, 60));

        btnRegresar.setText("Salir");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 130, 40));

        btnVerTurnos.setText("Ver Turnos");
        btnVerTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTurnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 250, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/⚛️ Fondamentaux (Community)-1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Panel de Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtSoliAusenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSoliAusenciaActionPerformed
       try {
           //validar que el empleado esta inicializado
           if(this.empleadoLogueado == null){
               JOptionPane.showMessageDialog(this, "Error: no hay Info del empleado", "Error de Sesion", JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           //Obtener el nombre de usuario
           String nombreUsuario = this.empleadoLogueado.getUsuario(); 
           //Crea y muestra el formulario
           SolicitudesEmpleadosForm solicitudesForm = new SolicitudesEmpleadosForm(nombreUsuario);
           solicitudesForm.setVisible(true);
           this.dispose();
               
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Error al abrir solicitudes" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
       }
    }//GEN-LAST:event_ButtSoliAusenciaActionPerformed

    private void ButtMarcajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtMarcajeActionPerformed
        MarcajeForm marcajeForm = new MarcajeForm(empleadoLogueado);
        marcajeForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtMarcajeActionPerformed


    private void ButtConsultarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtConsultarTurnoActionPerformed
        
    }//GEN-LAST:event_ButtConsultarTurnoActionPerformed


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVerTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTurnosActionPerformed
        AsignacionTurnosEmpleado ventanaTurnos = new AsignacionTurnosEmpleado(this.empleadoLogueado);
        ventanaTurnos.setVisible(true);
    }//GEN-LAST:event_btnVerTurnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtMarcaje;
    private javax.swing.JButton ButtSoliAusencia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerTurnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
