/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;
import javax.swing.JOptionPane;
import screen.MarcajeForm;
import model.Empleado;
import screen.AsignacionTurnosEmpleado;
/**
 *
 * @author jorgmms
 */
public class PanelDeEmpleado extends javax.swing.JFrame {

    // Variable para guardar al empleado (ya deberías tenerla)
    private Empleado empleadoLogueado;

    /**
     * Constructor que recibe al empleado que inició sesión.
     */
    public PanelDeEmpleado(Empleado empleado) {
        // 1. Inicializa los componentes visuales del formulario. ¡Esta línea es vital!
        initComponents();
        
        // 2. Guarda el objeto del empleado que recibiste para usarlo más tarde.
        this.empleadoLogueado = empleado;
        
        // 3. (Opcional) Usa los datos del empleado para personalizar la ventana.
        this.setTitle("Panel de " + this.empleadoLogueado.getNombre());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtMarcaje = new javax.swing.JButton();
        ButtSoliAusencia = new javax.swing.JButton();
        ButtConsultarTurno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVerTurnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtMarcaje.setText("Marcaje");
        ButtMarcaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtMarcajeActionPerformed(evt);
            }
        });
        getContentPane().add(ButtMarcaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 280, 60));

        ButtSoliAusencia.setText("Solicitud De Ausencia");
        ButtSoliAusencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtSoliAusenciaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtSoliAusencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 280, 60));

        ButtConsultarTurno.setText("Consultar Cambio de turno");
        ButtConsultarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtConsultarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtConsultarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 280, 60));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 130, 50));

        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Panel de Empleado");
        jPanel1.add(jLabel1);

        btnVerTurnos.setText("Ver Turnos");
        btnVerTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTurnosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTurnos);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtSoliAusenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSoliAusenciaActionPerformed
       SolicitudesEmpleadosForm solicitudesForm = new SolicitudesEmpleadosForm(this.empleadoLogueado.getUsuario());
        solicitudesForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtSoliAusenciaActionPerformed

    private void ButtMarcajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtMarcajeActionPerformed
        MarcajeForm marcajeForm = new MarcajeForm(empleadoLogueado);
        marcajeForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtMarcajeActionPerformed

    private void ButtConsultarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtConsultarTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtConsultarTurnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTurnosActionPerformed
        AsignacionTurnosEmpleado ventanaTurnos = new AsignacionTurnosEmpleado(this.empleadoLogueado);
        ventanaTurnos.setVisible(true);
    }//GEN-LAST:event_btnVerTurnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtConsultarTurno;
    private javax.swing.JButton ButtMarcaje;
    private javax.swing.JButton ButtSoliAusencia;
    private javax.swing.JButton btnVerTurnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
