package screen;

import screen.PanelDeEmpleado;
import dao.SolicitudDAO;
import model.Solicitud;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Erick
 */
public class SolicitudesEmpleadosForm extends javax.swing.JFrame {
    // Guarda el nombre de usuario de quien inició sesión.
    private final String usuarioLogueado;
    // Instancia del DAO para interactuar con el archivo de solicitudes.
    private final SolicitudDAO solicitudDAO;
   
   
  public SolicitudesEmpleadosForm(String usuario) { // <-- Se corrige aquí
        initComponents(); // Este método es generado por NetBeans.
        
        // Inicializa las variables importantes.
        this.usuarioLogueado = usuario;
        this.solicitudDAO = new SolicitudDAO();
        
        // Configura los elementos del formulario.
        configurarFormulario();
    }
  
    private void configurarFormulario() {
        this.setTitle("Portal de Empleado");
        this.setLocationRelativeTo(null); // Centra la ventana.
        lblBienvenido.setText("Bienvenido, " + this.usuarioLogueado);
        
        // Define las opciones para el ComboBox.
        String[] opciones = {
            "Permiso Personal",
            "Vacaciones",
            "Citas al IGSS",
            "Licencia de cumpleaños (1 día)",
            "Suspensión Laboral",
            "Otros"
        };
        // Asigna las opciones al modelo del ComboBox.
        comboTipoSolicitud.setModel(new DefaultComboBoxModel<>(opciones));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        lblInstruccion = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        comboTipoSolicitud = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 80, 40));

        lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInstruccion.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruccion.setText("Selecciona el tipo de permiso que necesitas");
        jPanel1.add(lblInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        lblBienvenido.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("Bienvenido ");
        jPanel1.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 480, -1));

        comboTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permiso Personal", "Vacaciones", "Citas al IGSS", "Licencia de cumpleaños (1 día)", "Suspensión Laboral", "Otros", " " }));
        jPanel1.add(comboTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 270, 40));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 160, 47));

        lblTitulo.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Frame 2267.png"))); // NOI18N
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 1040, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PNG/Fondo_principal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       // 1. Obtiene la opción seleccionada del ComboBox.
        String tipoSeleccionado = (String) comboTipoSolicitud.getSelectedItem();
        
        // 2. Crea un nuevo objeto Solicitud con los datos.
        Solicitud nuevaSolicitud = new Solicitud();
        nuevaSolicitud.setUsuario(this.usuarioLogueado);
        nuevaSolicitud.setTipo(tipoSeleccionado);
        nuevaSolicitud.setJustificacion(tipoSeleccionado); // Usamos el tipo como justificación por simplicidad.
        nuevaSolicitud.setFecha(LocalDate.now()); // Establece la fecha actual.
        nuevaSolicitud.setEstado("Pendiente"); // Todas las nuevas solicitudes inician como "Pendiente".

        // 3. Intenta guardar la solicitud usando el DAO.
        try {
            solicitudDAO.guardarSolicitud(nuevaSolicitud);
            JOptionPane.showMessageDialog(this, 
                "Tu solicitud ha sido enviada correctamente.", 
                "Solicitud Enviada", 
                JOptionPane.INFORMATION_MESSAGE);
            
            
            
        } catch (IOException e) {
            // Muestra un mensaje de error si algo sale mal al guardar.
            JOptionPane.showMessageDialog(this, 
                "Error al guardar la solicitud: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprime el error completo en la consola para depuración.
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       try {
        PanelDeEmpleado Panel = new PanelDeEmpleado(usuarioLogueado);
        Panel.setVisible(true);
       
       this.dispose();
       
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al regresar al panel" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
      e.printStackTrace();

      }
       
    }//GEN-LAST:event_btnRegresarActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudesEmpleadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            // Llama al constructor correcto con un usuario de ejemplo para pruebas
            new SolicitudesEmpleadosForm("").setVisible(true);
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboTipoSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
