package screen;

import dao.SolicitudDAO;
import model.Solicitud;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Erick
 */
public class SolicitudesEmpleadosForm extends javax.swing.JFrame {
    // Guarda el nombre de usuario de quien inició sesión.
    private final String usuarioLogueado;
    // Instancia del DAO para interactuar con el archivo de solicitudes.
    private final SolicitudDAO solicitudDAO;
   
   
  public SolicitudesEmpleadosForm(String usuario) { // <-- Se corrige aquí
        initComponents(); // Este método es generado por NetBeans.
        
        // Inicializa las variables importantes.
        this.usuarioLogueado = usuario;
        this.solicitudDAO = new SolicitudDAO();
        
        // Configura los elementos del formulario.
        configurarFormulario();
    }
  
    private void configurarFormulario() {
        this.setTitle("Portal de Empleado");
        this.setLocationRelativeTo(null); // Centra la ventana.
        lblBienvenido.setText("Bienvenido, " + this.usuarioLogueado);
        
        // Define las opciones para el ComboBox.
        String[] opciones = {
            "Permiso Personal",
            "Vacaciones",
            "Citas al IGSS",
            "Licencia de cumpleaños (1 día)",
            "Suspensión Laboral",
            "Otros"
        };
        // Asigna las opciones al modelo del ComboBox.
        comboTipoSolicitud.setModel(new DefaultComboBoxModel<>(opciones));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        comboTipoSolicitud = new javax.swing.JComboBox<>();
        lblInstruccion = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        lblTitulo.setText("Solicitudes de Ausencia");

        lblBienvenido.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido ");

        comboTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permiso Personal", "Vacaciones", "Citas al IGSS", "Licencia de cumpleaños (1 día)", "Suspensión Laboral", "Otros", " " }));

        lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruccion.setText("Selecciona el tipo de permiso que necesitas");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInstruccion)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGap(154, 154, 154))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBienvenido)
                .addGap(28, 28, 28)
                .addComponent(lblInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       // 1. Obtiene la opción seleccionada del ComboBox.
        String tipoSeleccionado = (String) comboTipoSolicitud.getSelectedItem();
        
        // 2. Crea un nuevo objeto Solicitud con los datos.
        Solicitud nuevaSolicitud = new Solicitud();
        nuevaSolicitud.setUsuario(this.usuarioLogueado);
        nuevaSolicitud.setTipo(tipoSeleccionado);
        nuevaSolicitud.setJustificacion(tipoSeleccionado); // Usamos el tipo como justificación por simplicidad.
        nuevaSolicitud.setFecha(LocalDate.now()); // Establece la fecha actual.
        nuevaSolicitud.setEstado("Pendiente"); // Todas las nuevas solicitudes inician como "Pendiente".

        // 3. Intenta guardar la solicitud usando el DAO.
        try {
            solicitudDAO.guardarSolicitud(nuevaSolicitud);
            JOptionPane.showMessageDialog(this, 
                "Tu solicitud ha sido enviada correctamente.", 
                "Solicitud Enviada", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Opcional: Cierra el formulario después de enviar la solicitud.
            this.dispose();
            
        } catch (IOException e) {
            // Muestra un mensaje de error si algo sale mal al guardar.
            JOptionPane.showMessageDialog(this, 
                "Error al guardar la solicitud: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprime el error completo en la consola para depuración.
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudesEmpleadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            // Llama al constructor correcto con un usuario de ejemplo para pruebas
            new SolicitudesEmpleadosForm("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> comboTipoSolicitud;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
